#[tool.pytest.ini_options]
#addopts = "--cov-config=coverage.cfg --cov-report term-missing"
#testpaths = [
#    "app1_simple_flask/tests",
#    "app2_flask_sqlalchemy/tests",
#]

[tool.mypy]
mypy_path = "."
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true
exclude = "(migrations|venv)"